<h1>Registro</h1>

<?php if (!empty($errores)): ?>
    <ul style="color:red;">
        <?php foreach ($errores as $e): ?>
            <li><?= $e ?></li>
        <?php endforeach; ?>
    </ul>
<?php endif; ?>

<form method="post">
    <input type="text" name="dni" placeholder="DNI" required><br><br>
    <input type="text" name="nombre" placeholder="Nombre" required><br><br>
    <input type="text" name="apellidos" placeholder="Apellidos" required><br><br>
    <input type="number" name="numero_empresa" placeholder="Número empresa" required><br><br>
    <input type="email" name="email" placeholder="Email" required><br><br>
    <input type="password" name="password" placeholder="Contraseña" required><br><br>
    <input type="password" name="confirm_password" placeholder="Repetir contraseña" required><br><br>

    <button type="submit">Registrarme</button>
</form>

<a href="index.php?controller=auth&action=login">Ya tengo cuenta</a>
